backend/home/urls.py
from django.urls import path

from .views import index, chat
app_name = "home"

urlpatterns = [
    path('', index, name="home"),
    path('chat/', chat, name="chat"),
    
]


backend/products/urls.py
from django.urls import path, include

from .views import product_detail, products, basket, basket_add, basket_remove, productCategory,SearchResultsView
app_name = "products"




urlpatterns = [
    path('detail/', products, name="detail"),
    path('product/<int:pk>/', product_detail, name='product_detail'),
    path('savat/', basket, name="savat"),
    path('basket/<int:product_id>', basket_add, name="basketadd"),
    path('basket/<int:basket_id>', basket_remove, name="basketremove"),
    path('category/', productCategory, name="category"),
    path("search/", SearchResultsView.as_view(), name="search"),
]

backend/zamonshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),

    path('', include('home.urls', namespace="home")),
    path('users/', include('users.urls', namespace="users")),
    path('orders/', include('orders.urls', namespace="orders")),
    path('product/', include('products.urls', namespace="products")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }), ]

backend/home/models.py
from django.db import models

from products.models import Category


class Banner(models.Model):
    title = models.CharField(max_length=50, verbose_name="Nomi")
    image = models.ImageField(upload_to="banner/%Y/%m/%d", height_field=None, width_field=None, max_length=None)

    def __str__(self):
        return self.title


class SwipperBanner(models.Model):
    title = models.CharField(max_length=50, verbose_name="Nomi")
    image = models.ImageField(upload_to="bnr_swiper/%Y/%m/%d", height_field=None, width_field=None, max_length=None)

    def __str__(self):
        return self.title
    

class TwoTanla(models.Model):
    category = models.ForeignKey(Category, verbose_name="2 Category", on_delete=models.CASCADE)

    def __str__(self):
        return self.category.name
    
    
    

backend/home/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required


from .models import Banner, SwipperBanner, TwoTanla
from products.models import Category, Product,Basket

# Create your views here.


def index(request, cat_id=None):

    categories = Category.objects.filter(children=None)
    # baskets = Basket.objects.filter(user=request.user)
    products = Product.objects.filter(category__id=cat_id) if cat_id else Product.objects.all().order_by("-id")[:10]

    context = {
        "categories": categories,
        "products": products,
        "banner": Banner.objects.all().order_by("-id")[:5],
        "swipe_banner": SwipperBanner.objects.all().order_by("-id")[:5],
        "tanlangan_banner": TwoTanla.objects.all().order_by("-id")[:2],
        # "total_quantity": sum(basket.quantity for basket in baskets),

    }

    return render(request, 'home/index.html', context)



def chat(request):
    return render(request, "chat/chat.html")


backend/templates/home/serach.html
{% extends 'home/base.html' %}
{% block content %}

<h1>Search Results</h1>
<div class="productInfo">

    <!-- Mahsulotlar -->

    <div class="Products">
        {% for prod in object_list %}
        
        <div class="product">
            <!-- <div class="sale">
                <span>20%/sale</span>
            </div> -->
            <a href="{% url "products:product_detail" prod.id %}">
                <div class="img">
                    <img src="{{prod.image.image.url}}" alt="" />
                </div>
            </a>
            <div class="poductInfo">
                <a style="text-decoration: none;" href="{% url "products:product_detail" prod.id %}">
                <p class="name" style="font-size: 18px; width: 100%">{{prod.name}}</p>
                </a>
                <p class="prodDesck" style="color: #5e5e5e;">{{prod.category.name}}</p>
                <p style="text-decoration:line-through; color: #8f8f8f; transform: translateY(5px); font-size: 14px;">{{prod.old_price}} so'm</p>
                <div class="sum">
                    <p class="hozirgi" style="font-weight: 500;">{{prod.price}} so'm</p>
                    <a href="{% url "products:basketadd" prod.id %}">
                    <div class="korish">
                        <i class="fa-solid fa-cart-shopping" style="color: #ffffff;"></i>
                    </div>
                    </a>
                </div>
            </div>
        </div>

        {% endfor %}


    </div>
</div>
{% endblock content %}