backend/home/urls.py
from django.urls import path

from .views import index, chat
app_name = "home"

urlpatterns = [
    path('', index, name="home"),
    path('chat/', chat, name="chat"),
    
]


backend/users/urls.py
from django.urls import path, include
from rest_framework import routers, serializers, viewsets

from . import views
from rest_framework import routers, serializers, viewsets
from rest_framework_simplejwt.views import (
    TokenRefreshView,
    
)

from . import views


# router = routers.DefaultRouter()
# router.register(r'', views.UserSet)
# router.register(r'api/token/', "users")


app_name = 'users'

urlpatterns = [
    # path('', include(router.urls)),
    # path('api/token/', views.CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    # path('api/auth/register/', views.UserCreate.as_view(), name='register'),
    # path('register/', views.UserRegistrationView.as_view()),

    path('token/', views.MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('register/', views.registration, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profil, name='profile'),
    path("otp/<uid>/", views.otp, name="otp"),

    path('myproduct/', views.myproduct, name="myproduct"),
    path('mylocation/' , views.mylocation , name="mylocation"),
    path('', views.profil , name="users"),

]


backend/zamonshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),

    path('', include('home.urls', namespace="home")),
    path('users/', include('users.urls', namespace="users")),
    path('orders/', include('orders.urls', namespace="orders")),
    path('product/', include('products.urls', namespace="products")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }), ]

backend/users/models.py
import uuid
from django.db import models

from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', null=True, blank=True)
    phone = models.CharField(max_length=23, blank=True, null=True)

    # adress dastavki


class Profile(models.Model):
    user = models.OneToOneField(to=User, on_delete=models.CASCADE, related_name='profile')
    phone_number = models.CharField(max_length=113)
    otp = models.CharField(max_length=123, null=True, blank=True)
    uid = models.UUIDField(default=uuid.uuid4)
    
    USERNAME_FIELD = 'user'

    def __str__(self) -> str:
        return self.user.username

backend/users/forms.py
from django import forms

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User, Profile

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Ism kiriting'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Parol kiriting'}))
    
    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    user = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Ism kiriting'}))

    phone_number = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'telefon kiriting'}))


    class Meta:
        model = Profile
        fields = ('user', 'phone_number', 'otp','uid')
    

class UserProfileForm(UserChangeForm):
    phone = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Telefon raqam'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Ismingizni kiriting'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Familiyangiz'}))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Ismingiz'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={
        'placeholder': 'email'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={
        'placeholder': 'image'}), required=False)


    class Meta:
        model = User
        fields = ('phone', 'first_name', 'last_name', 'username', 'email', 'image')


# class UserRegistrationForm(UserCreationForm):
#     username = forms.CharField(widget=forms.TextInput(attrs={
#         'placeholder': 'Ism kiriting'}))
#     last_name = forms.CharField(widget=forms.TextInput(attrs={
#         'placeholder': 'Familiyani kiriting'}))
#     phone = forms.CharField(widget=forms.TextInput(attrs={
#         'placeholder': 'telefon kiriting'}))
#     email = forms.EmailField(widget=forms.TextInput(attrs={
#         'placeholder': 'email kiriting'}))
#     password1 = forms.CharField(widget=forms.PasswordInput(attrs={
#         'placeholder': 'parol kiriting'}))
#     password2 = forms.CharField(widget=forms.PasswordInput(attrs={
#         'placeholder': 'parolni tastiqlang'}))

#     class Meta:
#         model = User
#         fields = ('username', 'last_name', 'phone','email', 'password1', 'password2')

backend/users/views.py
import random
import time
import re
from django.db import IntegrityError
from django.forms import ValidationError

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.sessions.backends.db import SessionStore
from django.contrib import auth, messages
from users.forms import UserProfileForm

from users.mixins import SendSmsApiWithEskiz


from .serializers import UserSerializer, MyTokenObtainPairSerializer

from .models import User, Profile

from rest_framework import generics
from rest_framework.permissions import AllowAny
from rest_framework import routers, serializers, viewsets
from rest_framework_simplejwt.views import TokenObtainPairView
from rest_framework.permissions import AllowAny

from rest_framework.decorators import api_view
from rest_framework.response import Response

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from .serializers import MyTokenObtainPairSerializer, RegisterSerializer

def is_valid_uzbek_phone_number(phone_number):
    pattern = r'^\d{9}$'
    return bool(re.match(pattern, phone_number))


@login_required
def profil(request):
    if request.method == 'POST':
        form = UserProfileForm(instance=request.user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
        else:
            print(form.errors)
    else:
        form = UserProfileForm(instance=request.user)
    
    context = {

        "title": "Profile",
        "form": form,
    }
    return render(request , 'users/profil.html')


@login_required
def myproduct(request):
    return render(request , 'users/myproduct.html')


@login_required
def mylocation(request):
    return render(request , 'users/mylocation.html')


# otp login
def login_view(request):
    if request.method == 'POST':
        phone_number = request.POST.get('phone_number')

        if is_valid_uzbek_phone_number(phone_number):

        
            profile = Profile.objects.filter(phone_number=phone_number).first()
            if not profile:
                return HttpResponseRedirect(reverse('users:register'))


            session = SessionStore(request.session.session_key)
            last_otp_time = session.get('last_otp_time')
            current_time = time.time()
            
            if last_otp_time and current_time - last_otp_time < 60:
                messages.warning(request, '60 sekunddan oldin yana bir marta so\'rov yuborishingiz mumkin')
                return redirect('users:login')
            

            try:
                profile.otp = random.randint(1000, 9999)
                profile.save()
                print(profile)
            except ValidationError as e:
                print(e)

            message_handler = SendSmsApiWithEskiz(message=str(profile.otp), phone=phone_number)
            message_handler.send()
            

            session['last_otp_time'] = current_time
            session.save()

            return redirect(f'/users/otp/{profile.uid}')
        
        else:
            messages.warning(request, 'uzbek raqam kiriting!!!\n')

    return render(request, 'users/login.html')


def logout_view(request):
    auth.logout(request)
    return redirect("/")


def registration(request):
    if request.method == 'POST':
        username = request.POST.get("username")
        phone_number = request.POST.get("phone_number")
        if is_valid_uzbek_phone_number(phone_number):
            try:

                user = User.objects.create(username=username)
                profile = Profile.objects.create(user=user, phone_number=phone_number)

                return HttpResponseRedirect(reverse('users:login'))
            
            except IntegrityError:
                messages.warning(request, 'Bunay username mavjud!!!')
                
        else:
            messages.warning(request, 'uzbek raqam kiriting!!!')


    return render(request, 'users/registration.html')


def otp(request, uid):
    if request.method == "POST":
        otp = request.POST.get('otp')
        profile = Profile.objects.get(uid = uid)
        if otp == profile.otp:
            auth.login(request, profile.user)
            return HttpResponseRedirect(reverse('users:profile'))
        
        return redirect(f'/users/otp/{uid}')
    return render(request, 'users/otp.html')





# class UserSet(viewsets.ModelViewSet):
#     queryset = User.objects.all()
#     serializer_class = UserSerializer


# class UserCreate(generics.CreateAPIView):
#     queryset = User.objects.all()
#     serializer_class = UserRegisterSerializer


# class UserRegistrationView(generics.CreateAPIView):
#     serializer_class = UserRegisterSerializer
#     permission_classes = (AllowAny,)


# class CustomTokenObtainPairView(TokenObtainPairView):
#     serializer_class = CustomTokenObtainPairSerializer

class MyTokenObtainPairView(TokenObtainPairView):
    serializer_class = MyTokenObtainPairSerializer

class RegisterView(generics.CreateAPIView):
    queryset = User.objects.all()
    permission_classes = (AllowAny,)
    serializer_class = RegisterSerializer


@api_view(['GET'])
def getRoutes(request):
    routes = [
        '/users/token/',
        '/users/register/',
        '/users/token/refresh/'
    ]
    return Response(routes)

backend/templates/users/login.html
{% extends 'home/base.html' %}

{% load static %}
<!-- no OTP-->
{% comment %} {% block content %}
    <div class="register">

        <div class="registerBox ">
            {% if messages or form.non_field_errors %}
                <div class="{% if messages %} orangemassageBar {% else %} redmassageBar {% endif %}">
                    {% if messages %}
                        {% for message in messages %}
                            <p>{{ message }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
            {% else %}
                {{ form.non_field_errors }}
            {% endif %}
            <span class="registerBoxTitle">Вход / Регистрация</span>
            <form method="POST">
                {% csrf_token %}
                <div class="registerInputs">
                    <div class="registerInputsChil">
                        <label for="">Введите имя</label>
                        <div class="registerInputsChilInput">
                            <i class="fa-regular fa-user"></i>
                            {{form.username}}
                        </div>
                    </div>
                    <div class="registerInputsChil">
                        <label for="">Пароль</label>
                        <div class="registerInputsChilInput">
                            <img src="{% static 'media/lock.svg' %}" alt="">
                            {{form.password}}
                        </div>
                    </div>
                </div>
                <div class="registerFooter">
                    <div class="registerFooterLoginNext">
                        <span>Создавать аккаунт</span><a href="{% url 'users:registration' %}">Регистрация</a>
                    </div>
                    <button type="submit">Входить</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}
{% endcomment %}

{% block content %}
    <div class="register">

        <div class="registerBox">
            {% if messages or form.non_field_errors %}
                <div class="{% if messages %} orangemassageBar {% else %} redmassageBar {% endif %}">
                    {% if messages %}
                        {% for message in messages %}
                            <p>{{ message }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
            {% else %}
                {{ form.non_field_errors }}
            {% endif %}
            <span class="registerBoxTitle">Входить</span>
            <form method="POST">
                {% csrf_token %}
                <div class="registerInputs">
                    <div class="registerInputsChil">
                        <label for="">Отправим смс с кодом подтверждения</label>
                        <div class="registerInputsChilInput">
                            <p class="telTitle">+998</p>
                            <input name="phone_number" type="text"  placeholder="00 000-00-00">
                        </div>
                    </div>
                </div>
                <div class="registerFooter">
                    <div class="registerFooterLoginNext">
                        <span>Создавать аккаунт</span><a href="{% url 'users:register' %}">Регистрация</a>
                    </div>
                    <button type="submit">Получить код</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}


backend/templates/users/mylocation.html
{% extends 'home/base.html' %}

{% load static %}
{% block content %}
    <div class="userProfil">
        <div class="userProfilLeft">
            <a href="{% url 'users:users' %}"><button><i class="fa-solid fa-user"></i><span>Персональная данные</span></button></a>
            <a href="{% url 'users:myproduct' %}"><button><i class="fa-solid fa-box"></i><span>Мои заказы</span></button></a>
            <a href="{% url 'users:mylocation' %}"><button class="activeProfil"><i class="fa-solid fa-truck-fast"></i><span>дрес доставки</span></button></a>
            <a href=""><button><i class="fa-solid fa-right-from-bracket fa-rotate-180" style="color: red; background: rgba(255, 0, 0, 0.168);"></i><span>Выйти из профиля</span></button></a>
        </div>
        <form class="userAdress">
            <span class="userAdressTItle">Адрес доставки</span>
            <div class="addAdress">
                <div class="addAdressChil">
                    <label for="">Город</label>
                    <select name="" id="">
                        <option value="">Xorazm</option>
                    </select>
                </div>
                <div class="addAdressChil">
                    <label for="">Район</label>
                    <select name="" id="">
                        <option value="">Urganch</option>
                        <option value="">Xiva</option>
                        <option value="">Shovot</option>
                        <option value="">Xonqa</option>
                        <option value="">Bog'ot</option>
                        <option value="">Yangi Ariq</option>
                        <option value="">Gurlan</option>
                    </select>
                </div>
                <div class="addAdressChil">
                    <label for="">Дом</label>
                    <input type="text">
                </div>
                <div class="addAdressChil">
                    <label for="">Подъезд</label>
                    <input type="text">
                </div>
                <div class="addAdressChil">
                    <label for="">Этаж</label>
                    <input type="text">
                </div>
                <div class="addAdressChil">
                    <label for="">Квартира</label>
                    <input type="text">
                </div>
                <div class="addAdressChil">
                    <label for="">Пароль домофона</label>
                    <input type="text">
                </div>
            </div>
            <button type="submit" class="userAdressSave">Save</button>
        </form>
    </div>
{% endblock content %}

backend/templates/users/myproduct.html
{% extends 'home/base.html' %}

{% load static %}
{% block content %}

<div class="userProfil">
    <div class="userProfilLeft">
        <a href="{% url 'users:users' %}"><button><i class="fa-solid fa-user"></i><span>Персональная
                    данные</span></button></a>
        <a href="{% url 'users:myproduct' %}"><button class="activeProfil"><i class="fa-solid fa-box"></i><span>Мои
                    заказы</span></button></a>
        <a href="{% url 'users:mylocation' %}"><button><i class="fa-solid fa-truck-fast"></i><span>дрес доставки</span></button></a>
        <a href=""><button><i class="fa-solid fa-right-from-bracket fa-rotate-180"
                    style="color: red; background: rgba(255, 0, 0, 0.168);"></i><span>Выйти из
                    профиля</span></button></a>
    </div>
    <div class="myproducts">
        <span class="myproducts_title">Мои заказы</span>
        <div class="myproductsCat">
            <li class="myproductsCatLI">Все заказы</li>
            <li class="myproductsCatLI">Активный</li>
            <li class="myproductsCatLI">Завершенный</li>
            <li class="myproductsCatLI">Отменено</li>
            <li class="myproductsCatLI">Рассрочка</li>
        </div>
        <div class="myproducts_products">
            <div class="myproducts_products_product">
                <div>
                    <img src="https://parfumstock.uz/thumb/2/eBNXkH1T3xY0SHSSoiCEYg/r/d/3348901520065.jpg" alt="">
                    <span class="myproducts_products_product_productName">Dior Sauvage Parfum 100 ml</span>
                </div>
                <span class="myproducts_products_product_Shtuk">3x</span>
                <span class="myproducts_products_product_Price">12.000.000 sum</span>
            </div>
            <div class="myproducts_products_product">
                <div>
                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRA9v3VjZP5HfcNZEa1iC0kBe69TUxZSCE6Ug&usqp=CAU" alt="">
                    <span class="myproducts_products_product_productName">Dior Sauvage Parfum 100 ml</span>
                </div>
                <span class="myproducts_products_product_Shtuk">3x</span>
                <span class="myproducts_products_product_Price">12.000.000 sum</span>
            </div>
        </div>
    </div>
</div>
<script>
    const lists = document.querySelectorAll('.myproductsCatLI')

    // lists.forEach(item => {
    //     item.onclick = () => {
    //         item.classList.add('active')
    //     }
    // })
    lists[0].classList.add('active')

    lists[0].onclick = () => {
        lists[0].classList.add('active')
        lists[1].classList.remove('active')
        lists[2].classList.remove('active')
        lists[3].classList.remove('active')
        lists[4].classList.remove('active')
    }
    lists[1].onclick = () => {
        lists[1].classList.add('active')
        lists[0].classList.remove('active')
        lists[2].classList.remove('active')
        lists[3].classList.remove('active')
        lists[4].classList.remove('active')
    }
    lists[2].onclick = () => {
        lists[0].classList.remove('active')
        lists[2].classList.add('active')
        lists[1].classList.remove('active')
        lists[3].classList.remove('active')
        lists[4].classList.remove('active')
    }
    lists[3].onclick = () => {
        lists[3].classList.add('active')
        lists[0].classList.remove('active')
        lists[1].classList.remove('active')
        lists[4].classList.remove('active')
        lists[2].classList.remove('active')
    }
    lists[4].onclick = () => {
        lists[4].classList.add('active')
        lists[0].classList.remove('active')
        lists[1].classList.remove('active')
        lists[2].classList.remove('active')
        lists[3].classList.remove('active')
    }

</script>

{% endblock content %}

backend/templates/users/otp.html
{% extends 'home/base.html' %}

{% load static %}
{% block content %}
    <div class="register">

        <div class="registerBox">
            {% if messages or form.non_field_errors %}
                <div class="{% if messages %} orangemassageBar {% else %} redmassageBar {% endif %}">
                    {% if messages %}
                        {% for message in messages %}
                            <p>{{ message }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
            {% else %}
                {{ form.non_field_errors }}
            {% endif %}
            <span class="registerBoxTitle">Введите код</span>
            <form method="POST">
                {% csrf_token %}
                <div class="registerInputs">
                    <div class="registerInputsChil">
                        <label style="width: 328px;" for="">Для подтверждения телефона отправили 4-значный код на +998 91 437-37-90</label>
                        <div class="registerInputsChilInput">
                            <input name="otp" type="number" >
                        </div>
                    </div>
                </div>
                <div class="registerFooter">
                    <div class="registerFooterLoginNext">
                        <span>Создавать аккаунт</span><a href="{% url 'users:register' %}">Регистрация</a>
                    </div>
                    <button type="submit">Входить</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}


backend/templates/users/profil.html
{% extends 'home/base.html' %}

{% load static %}
{% block content %}

<div class="userProfil">
    <div class="userProfilLeft">
        <a href=""><button class="activeProfil"><i class="fa-solid fa-user"></i><span>Персональная данные</span></button></a>
        <a href="{% url 'users:myproduct' %}"><button><i class="fa-solid fa-box"></i><span>Мои заказы</span></button></a>
        <a href="{% url 'users:mylocation' %}"><button><i class="fa-solid fa-truck-fast"></i><span>дрес доставки</span></button></a>
        <a href="{% url 'users:logout' %}"><button><i class="fa-solid fa-right-from-bracket fa-rotate-180" style="color: red; background: rgba(255, 0, 0, 0.168);"></i><span>Выйти из профиля</span></button></a>
    </div>
    <form class="userInfos">
        {% csrf_token %}
        <span class="userInfos_Title">Персональная данные</span>
        <div class="inInfos">
            <div class="inInfosChil">
                <label for="">Ism</label>
                <input type="text" placeholder="ism">
            </div>
            <div class="inInfosChil">
                <label for="">Familya</label>
                <input type="text" placeholder="Familya">
            </div>
            <div class="inInfosChil">
                <label for="">Tug'ulgan Sana</label>
                <input type="date" placeholder="Tug'ilgan Sana">
            </div>
            <div class="inInfosChil">
                <label for="">Email</label>
                <input type="email" placeholder="Email">
            </div>
            <div class="inInfosChil">
                <label for="">Jins</label>
                <select class="inInfosChil">
                    <option value disabled hidden></option>
                    <option value="">Erkak</option>
                    <option value="">Ayol</option>
                    <option value="">Gey</option>
                </select>
            </div>
            <div class="inInfosChil">
                <label for="">Telfon</label>
                <input type="tel" placeholder="+998 91 943 33 33">
            </div>
        </div>
        <button type="submit" class="userInfosSaveBtn">Save</button>
    </form>
</div>

{% endblock content %}


backend/templates/users/registration.html
{% extends 'home/base.html' %}
{% load static %}


{% block content %}
{% if messages %}
    {% for message in messages %}
    
    <div class="massageBar">
        {{ message | safe }}
    </div>
    {% endfor %}
{% endif %}
<div class="register">
    <form action='{% url 'users:register' %}' method='post'>
        {% csrf_token %}
        <div class="loginBox">
            <span class="registerBoxTitle">Регистрация</span>
            <div class="registerInputs">
                <div class="registerInputsChil">
                    <label for="">Ismingizni kiriting</label>
                    <div class="registerInputsChilInput">
                        <i class="fa-regular fa-user"></i>
                        <input name="username" type="text" placeholder="Username">
                    </div>
                </div>
                <div class="registerInputsChil">
                    <label for="">Telefon raqam</label>
                    <div class="registerInputsChilInput">
                        <p class="telTitle">+998</p>
                        <input name="phone_number" type="phone" placeholder="00 000-00-00">
                    </div>
                </div>
                <div class="registerFooter">
                    <div class="registerFooterLoginNext">
                        <span>У меня есть аккаунт</span><a href="/login">Войти</a>
                    </div>
                    <button>Зарегистрироваться</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock content %}
