backend/home/urls.py
from django.urls import path

from .views import index, chat
app_name = "home"

urlpatterns = [
    path('', index, name="home"),
    path('chat/', chat, name="chat"),
    
]


backend/orders/urls.py
from django.urls import path, include

from .views import savat, order

app_name = "orders"

urlpatterns = [
    path('', savat, name="savat"),
    path('order/', order, name="order"),
]


backend/zamonshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),

    path('', include('home.urls', namespace="home")),
    path('users/', include('users.urls', namespace="users")),
    path('orders/', include('orders.urls', namespace="orders")),
    path('product/', include('products.urls', namespace="products")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }), ]

backend/orders/models.py
from django.db import models

# Create your models here.

backend/orders/views.py
from django.shortcuts import render

# Create your views here.

def savat(request):
    return render(request, 'orders/savat.html')


def order(request):
    return render(request, 'orders/order.html')


backend/templates/orders/order.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}

<div class="Orders">
    <h1>1. Как вы хотите получить заказ?</h1>
    <div class="zakaz">

        <div class="zakazBtn const1">
            <img src="{% static 'images/Vector2.svg' %}" alt="">
            <p>Самовызов</p>
        </div>
        <div class="zakazBtn const2">
            <img src="{% static 'images/boxtick.svg' %}" alt="">
            <p>Доставка</p>
        </div>
    </div>
    <h1>2. Укажите адрес доставки</h1>
    <div class="gorod">

        <div class="selects">
            <p>Город</p>
            <select aria-placeholder="Выберите город" name="" id="">
                <option value="">Urgench</option>
                <option value="">Xonka</option>
                <option value="">shovot</option>
                <option value="">bog'ot</option>
            </select>
        </div>
        <div class="selects">
            <p>Полный адрес</p>
            <input type="text">
        </div>
    </div>
    <h1>3. Контактное имя</h1>
    <div class="gorod">
        <div class="selects">
            <p>Имя</p>
            <input type="text" placeholder="Ism">
        </div>
        <div class="selects">
            <p>Фамилия</p>
            <input type="text" placeholder="Familiya">
        </div>
        <div class="selects">
            <p>Телефон</p>
            <input type="text" placeholder="Telefon">
        </div>
        <div class="selects">
            <p>Дополнительный телефон</p>
            <input type="text" placeholder="Qo'shimcha telefon">
        </div>
    </div>
    <button class="order">
        <span class="default">Buyurtma berish</span>
        <span class="success">
            Buyurtmangiz qabul qilindi
            <svg viewBox="0 0 12 10">
                <polyline points="1.5 6 4.5 9 10.5 1"></polyline>
            </svg>
        </span>
        <div class="box"></div>
        <div class="truck">
            <div class="back"></div>
            <div class="front">
                <div class="window"></div>
            </div>
            <div class="light top"></div>
            <div class="light bottom"></div>
        </div>
        <div class="lines"></div>
    </button>
</div>

<script>

    const zakazBtn1 = document.querySelector('.const1')
    const zakazBtn2 = document.querySelector('.const2')

    zakazBtn1.onclick = function () {
        zakazBtn1.classList.add('zakazBtnAdd')
        zakazBtn2.classList.remove('zakazBtnAdd')

    }

    zakazBtn2.onclick = function () {
        zakazBtn1.classList.remove('zakazBtnAdd')
        zakazBtn2.classList.add('zakazBtnAdd')
    }



    const order = document.querySelector(".order");

    function handleOrderClick() {
        if (!order.classList.contains("animate")) {
            order.classList.add("animate");
            setTimeout(function () {
                order.classList.remove("animate");
            }, 10000);
        }
    }

    function init() {
        order.addEventListener("click", handleOrderClick);
    }

    init();


</script>

{% endblock content %}

backend/templates/orders/savat.html
{% extends 'home/base.html' %}
{% load static %}   
{% block content %}




<div class="Savat">
    <div class="karzinkaProducts">
        {% for bask in baskets %}
        <div class="karzinkaProduct">
            <div class="imgName">
                <img src="{{ bask.product.image.image.url }}" alt="">
                <p>{{ bask.product.name }}</p>
            </div>
            <div class="cunterPrice">
                <div class="counter">
                    <p>-</p>
                    <span>{{ bask.quantity }} </span>
                    <p>+</p>
                </div>
                <h5 class="price">{{ bask.de_json.sum }} so'm</h5>
            </div>
        </div>
        {% endfor %}

    </div>     
    <div class="addZakaz">
        <p class="buyurtma">Sizning buyurtmangiz <span>{{ total_quantity }}</span></p>
        <div class="allPrice">
            <span>Jami:</span>
            <p>{{ total_sum }} so`m</p>
        </div>
        <div class="zakazBtns">
            <p>Dokonga Qaytish</p>
            <p><a href="{% url 'orders:order' %}"> Sotib Olish</a> </p>
        </div>
    </div>
</div>


{% endblock content %}